version: '3.9'

networks:
  todo_network:
    external: true

services:
  todo-app:
    container_name: todo-app
    image: todo-app
    build:
      context: ../
      dockerfile: .infra/Dockerfile
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - todo_network