version: '3.9'

networks:
  todo_network:
    name: todo_network
    driver: bridge

services:
  todo-db:
    image: mongo
    container_name: todo-db
    environment:
      MONGO_INITDB_DATABASE: todo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - todo_network
